#!/bin/sh

current_path=`dirname $(readlink -f $0)`
prefix=`dirname $current_path`
logpath=$prefix/logs

if [ $1 = "clean" ]; then
	truncate $logpath/*.log --size 0
	exit
fi

if [ $1 = "error" ]; then
	tail -f $logpath/error.log
	exit
fi

if [ $1 = "access" ]; then
	tail -f $logpath/access.log
	exit
fi
